server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/longzai_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    name: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
      # 如果使用的是高于spring boot 2.6的版本，
      # 需要配置spring.main.allow-circular-references=true，
      # 从2.6开始Spring Boot 默认禁用了循环引用
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  main:
    allow-circular-references: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
#  修改成自己的 ak
    accessKey: aocb6zqr7TWnMLQQ0642EjSKCjFLEUdCGQU9v9z8
#   修改成自己的 Sk
    secretKey: VoDEi-YEW-G-HbFwOdK8m8YYIl31Bd8QwnthDFsl
#    空间名称
    bucket: xiangvlog
#   外链链接
    url: http://xiangvlog.xiang-xiao.com/

debug: true

